@startuml
!include .\\Program.puml
!include .\\Controllers\AgentsController.puml
!include .\\Controllers\BookingsController.puml
!include .\\Controllers\CartController.puml
!include .\\Controllers\CheckedInOutTimesController.puml
!include .\\Controllers\GuestsController.puml
!include .\\Controllers\HomeController.puml
!include .\\Controllers\ReceiptsController.puml
!include .\\Controllers\ReportsController.puml
!include .\\Controllers\RestaurantsController.puml
!include .\\Controllers\RoomsController.puml
!include .\\Controllers\RoomTypesController.puml
!include .\\Controllers\ServicesController.puml
!include .\\Controllers\TransactionsController.puml
!include .\\Data\ApplicationDbContext.puml
!include .\\Data\SeedData.puml
!include .\\Helpers\SessionHelper.puml
!include .\\Models\Agent.puml
!include .\\Models\Booking.puml
!include .\\Models\CheckedInCustomer.puml
!include .\\Models\CheckedInOutTime.puml
!include .\\Models\Employee.puml
!include .\\Models\ErrorViewModel.puml
!include .\\Models\Guest.puml
!include .\\Models\Item.puml
!include .\\Models\Receipt.puml
!include .\\Models\Restaurant.puml
!include .\\Models\Room.puml
!include .\\Models\RoomType.puml
!include .\\Models\Service.puml
!include .\\Models\Transaction.puml
!include .\\Data\Migrations\00000000000000_CreateIdentitySchema.puml
!include .\\Data\Migrations\00000000000000_CreateIdentitySchema.Designer.puml
!include .\\Data\Migrations\20220930160235_AddedAgent.puml
!include .\\Data\Migrations\20220930160235_AddedAgent.Designer.puml
!include .\\Data\Migrations\20221001091212_AddedGuest.puml
!include .\\Data\Migrations\20221001091212_AddedGuest.Designer.puml
!include .\\Data\Migrations\20221001092346_AddedRestaurant.puml
!include .\\Data\Migrations\20221001092346_AddedRestaurant.Designer.puml
!include .\\Data\Migrations\20221004073414_AddedBooking.puml
!include .\\Data\Migrations\20221004073414_AddedBooking.Designer.puml
!include .\\Data\Migrations\20221005142103_AddedCheckedInCheckedOutTime.puml
!include .\\Data\Migrations\20221005142103_AddedCheckedInCheckedOutTime.Designer.puml
!include .\\Data\Migrations\20221007011842_AddedCommentToBooking.puml
!include .\\Data\Migrations\20221007011842_AddedCommentToBooking.Designer.puml
!include .\\Data\Migrations\20221007065322_AddedRoomStatusUpdatedToBooking.puml
!include .\\Data\Migrations\20221007065322_AddedRoomStatusUpdatedToBooking.Designer.puml
!include .\\Data\Migrations\20221007083911_ChangeCheckedInCustomer.puml
!include .\\Data\Migrations\20221007083911_ChangeCheckedInCustomer.Designer.puml
!include .\\Data\Migrations\20221007142314_ChangedService.puml
!include .\\Data\Migrations\20221007142314_ChangedService.Designer.puml
!include .\\Data\Migrations\20221007155720_ChangedServiceTime.puml
!include .\\Data\Migrations\20221007155720_ChangedServiceTime.Designer.puml
!include .\\Data\Migrations\20221008014210_ChangedTransactionDate.puml
!include .\\Data\Migrations\20221008014210_ChangedTransactionDate.Designer.puml
!include .\\Data\Migrations\20221008050146_AddedCreatedDate.puml
!include .\\Data\Migrations\20221008050146_AddedCreatedDate.Designer.puml
!include .\\Data\Migrations\20221008071657_ChangedServicePriceToInt.puml
!include .\\Data\Migrations\20221008071657_ChangedServicePriceToInt.Designer.puml
!include .\\Data\Migrations\20221009101654_AddedReceipt.puml
!include .\\Data\Migrations\20221009101654_AddedReceipt.Designer.puml
!include .\\Data\Migrations\20221009112506_AddedHourlyPriceToRoomType.puml
!include .\\Data\Migrations\20221009112506_AddedHourlyPriceToRoomType.Designer.puml
!include .\\Data\Migrations\20221009142225_AddedTransactionTypeInReceipt.puml
!include .\\Data\Migrations\20221009142225_AddedTransactionTypeInReceipt.Designer.puml
!include .\\Data\Migrations\20221011164058_AddedService.puml
!include .\\Data\Migrations\20221011164058_AddedService.Designer.puml
!include .\\Data\Migrations\20221108134643_ChangedGuestAgentRoomOptional.puml
!include .\\Data\Migrations\20221108134643_ChangedGuestAgentRoomOptional.Designer.puml
!include .\\Data\Migrations\20221108141316_RemovedFloorLevelFromRoom.puml
!include .\\Data\Migrations\20221108141316_RemovedFloorLevelFromRoom.Designer.puml
!include .\\Data\Migrations\20221113012415_AddRoomPriceToBooking.puml
!include .\\Data\Migrations\20221113012415_AddRoomPriceToBooking.Designer.puml
!include .\\Data\Migrations\20221113045823_AddedGuestToRoom.puml
!include .\\Data\Migrations\20221113045823_AddedGuestToRoom.Designer.puml
!include .\\Data\Migrations\20221113060056_ChangeQuantityNullableInRestaurant.puml
!include .\\Data\Migrations\20221113060056_ChangeQuantityNullableInRestaurant.Designer.puml
!include .\\Data\Migrations\20221113060909_MakeRoomIdNullableInTransaction.puml
!include .\\Data\Migrations\20221113060909_MakeRoomIdNullableInTransaction.Designer.puml
!include .\\Data\Migrations\20221113061230_MakeAgentIdAndRoomIdNullableInReceipt.puml
!include .\\Data\Migrations\20221113061230_MakeAgentIdAndRoomIdNullableInReceipt.Designer.puml
!include .\\Data\Migrations\20221113061527_MakeGuestIdNullableInReceipt.puml
!include .\\Data\Migrations\20221113061527_MakeGuestIdNullableInReceipt.Designer.puml
!include .\\Data\Migrations\20221113111816_AddPhotosToGuestAgentEmployee.puml
!include .\\Data\Migrations\20221113111816_AddPhotosToGuestAgentEmployee.Designer.puml
!include .\\Data\Migrations\20221113115628_AddPhotoNameInGuestAgentEmployee.puml
!include .\\Data\Migrations\20221113115628_AddPhotoNameInGuestAgentEmployee.Designer.puml
!include .\\Data\Migrations\ApplicationDbContextModelSnapshot.puml
!include .\\Areas\Identity\Pages\Error.cshtml.puml
!include .\\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\obj\Debug\net6.0\HRMS.AssemblyInfo.puml
!include .\\obj\Debug\net6.0\HRMS.GlobalUsings.g.puml
!include .\\obj\Debug\net6.0\HRMS.MvcApplicationPartsAssemblyInfo.puml
!include .\\obj\Debug\net6.0\HRMS.RazorAssemblyInfo.puml
!include .\\obj\Debug\net6.0\UserSecretsAssemblyInfo.puml
!include .\\obj\Release\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\obj\Release\net6.0\HRMS.AssemblyInfo.puml
!include .\\obj\Release\net6.0\HRMS.GlobalUsings.g.puml
!include .\\obj\Release\net6.0\HRMS.MvcApplicationPartsAssemblyInfo.puml
!include .\\obj\Release\net6.0\HRMS.RazorAssemblyInfo.puml
!include .\\obj\Release\net6.0\UserSecretsAssemblyInfo.puml
!include .\\Areas\Identity\Pages\Account\AccessDenied.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ConfirmEmail.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ConfirmEmailChange.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ExternalLogin.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ForgotPassword.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ForgotPasswordConfirmation.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Lockout.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Login.cshtml.puml
!include .\\Areas\Identity\Pages\Account\LoginWith2fa.cshtml.puml
!include .\\Areas\Identity\Pages\Account\LoginWithRecoveryCode.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Logout.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Register.cshtml.puml
!include .\\Areas\Identity\Pages\Account\RegisterConfirmation.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ResendEmailConfirmation.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ResetPassword.cshtml.puml
!include .\\Areas\Identity\Pages\Account\ResetPasswordConfirmation.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ChangePassword.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\DeletePersonalData.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\Disable2fa.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\DownloadPersonalData.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\Email.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\EnableAuthenticator.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ExternalLogins.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\GenerateRecoveryCodes.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\Index.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ManageNavPages.puml
!include .\\Areas\Identity\Pages\Account\Manage\PersonalData.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ResetAuthenticator.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\SetPassword.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\ShowRecoveryCodes.cshtml.puml
!include .\\Areas\Identity\Pages\Account\Manage\TwoFactorAuthentication.cshtml.puml
@enduml
