@startuml
class ChangePasswordModel {
    + ChangePasswordModel(userManager:UserManager<IdentityUser>, signInManager:SignInManager<IdentityUser>, logger:ILogger<ChangePasswordModel>)
    + StatusMessage : string <<get>> <<set>>
    + <<async>> OnGetAsync() : Task<IActionResult>
    + <<async>> OnPostAsync() : Task<IActionResult>
}
class "UserManager`1"<T> {
}
class "SignInManager`1"<T> {
}
class "ILogger`1"<T> {
}
class InputModel {
    + OldPassword : string <<get>> <<set>>
    + NewPassword : string <<get>> <<set>>
    + ConfirmPassword : string <<get>> <<set>>
}
PageModel <|-- ChangePasswordModel
ChangePasswordModel --> "_userManager<IdentityUser>" "UserManager`1"
ChangePasswordModel --> "_signInManager<IdentityUser>" "SignInManager`1"
ChangePasswordModel --> "_logger<ChangePasswordModel>" "ILogger`1"
ChangePasswordModel --> "Input" InputModel
ChangePasswordModel +-- InputModel
@enduml
