@startuml
class ForgotPasswordModel {
    + ForgotPasswordModel(userManager:UserManager<IdentityUser>, emailSender:IEmailSender)
    + <<async>> OnPostAsync() : Task<IActionResult>
}
class "UserManager`1"<T> {
}
class InputModel {
    + Email : string <<get>> <<set>>
}
PageModel <|-- ForgotPasswordModel
ForgotPasswordModel --> "_userManager<IdentityUser>" "UserManager`1"
ForgotPasswordModel --> "_emailSender" IEmailSender
ForgotPasswordModel --> "Input" InputModel
ForgotPasswordModel +-- InputModel
@enduml
