@startuml
class RegisterConfirmationModel {
    + RegisterConfirmationModel(userManager:UserManager<IdentityUser>, sender:IEmailSender)
    + Email : string <<get>> <<set>>
    + DisplayConfirmAccountLink : bool <<get>> <<set>>
    + EmailConfirmationUrl : string <<get>> <<set>>
    + <<async>> OnGetAsync(email:string, returnUrl:string) : Task<IActionResult>
}
class "UserManager`1"<T> {
}
PageModel <|-- RegisterConfirmationModel
RegisterConfirmationModel --> "_userManager<IdentityUser>" "UserManager`1"
RegisterConfirmationModel --> "_sender" IEmailSender
@enduml
