@startuml
class RoomTypesController {
    + RoomTypesController(context:ApplicationDbContext)
    + <<async>> Index() : Task<IActionResult>
    + <<async>> Details(id:int?) : Task<IActionResult>
    + Create() : IActionResult
    + <<async>> Create(roomType:RoomType) : Task<IActionResult>
    + <<async>> Edit(id:int?) : Task<IActionResult>
    + <<async>> Edit(id:int, roomType:RoomType) : Task<IActionResult>
    + <<async>> Delete(id:int?) : Task<IActionResult>
    + <<async>> DeleteConfirmed(id:int) : Task<IActionResult>
    - RoomTypeExists(id:int) : bool
}
Controller <|-- RoomTypesController
RoomTypesController --> "_context" ApplicationDbContext
@enduml
