@startuml
class ServicesController {
    + ServicesController(context:ApplicationDbContext)
    + <<async>> Index() : Task<IActionResult>
    + <<async>> Details(id:int?) : Task<IActionResult>
    + Create() : IActionResult
    + <<async>> Create(service:Service, form:IFormCollection) : Task<IActionResult>
    + <<async>> Edit(id:int?) : Task<IActionResult>
    + <<async>> Edit(id:int, service:Service, form:IFormCollection) : Task<IActionResult>
    + <<async>> Delete(id:int?) : Task<IActionResult>
    + <<async>> DeleteConfirmed(id:int) : Task<IActionResult>
    - ServiceExists(id:int) : bool
}
Controller <|-- ServicesController
ServicesController --> "_context" ApplicationDbContext
@enduml
